// Code generated by mockery v2.53.4. DO NOT EDIT.

package mock

import mock "github.com/stretchr/testify/mock"

// handlerOptionFunc is an autogenerated mock type for the handlerOptionFunc type
type handlerOptionFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *handlerOptionFunc) Execute(_a0 *handler.handler) {
	_m.Called(_a0)
}

// newHandlerOptionFunc creates a new instance of handlerOptionFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newHandlerOptionFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *handlerOptionFunc {
	mock := &handlerOptionFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
