// Code generated by mockery v2.53.4. DO NOT EDIT.

package mock

import mock "github.com/stretchr/testify/mock"

// handlerOption is an autogenerated mock type for the handlerOption type
type handlerOption struct {
	mock.Mock
}

// apply provides a mock function with given fields: _a0
func (_m *handlerOption) apply(_a0 *handler.handler) {
	_m.Called(_a0)
}

// newHandlerOption creates a new instance of handlerOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newHandlerOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *handlerOption {
	mock := &handlerOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
