// Code generated by mockery v2.53.4. DO NOT EDIT.

package mock

import mock "github.com/stretchr/testify/mock"

// HandlerOptionFunc is an autogenerated mock type for the HandlerOptionFunc type
type HandlerOptionFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *HandlerOptionFunc) Execute(_a0 *handler.handler) {
	_m.Called(_a0)
}

// NewHandlerOptionFunc creates a new instance of HandlerOptionFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandlerOptionFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *HandlerOptionFunc {
	mock := &HandlerOptionFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
